# Generated by Django 4.0.3 on 2022-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider_Name', models.CharField(max_length=20)),
                ('Created_On', models.CharField(max_length=122)),
                ('Current_Start_Date', models.CharField(max_length=122)),
                ('Current_End_Date', models.CharField(max_length=122)),
                ('Is_Automatic_Payment_Enabled', models.CharField(max_length=122)),
                ('Last_Modified_On', models.CharField(max_length=122)),
                ('Status', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='subsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionID', models.CharField(max_length=20)),
                ('Amount_Paid', models.CharField(max_length=122)),
                ('Started_On', models.CharField(max_length=122)),
                ('Ends_On', models.CharField(max_length=122)),
                ('Invoice_File', models.CharField(max_length=122)),
            ],
        ),
    ]
