# Generated by Django 4.0.3 on 2022-04-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsdetails',
            name='subscriptionID',
        ),
        migrations.AlterField(
            model_name='subsdetails',
            name='Invoice_File',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
