# Generated by Django 4.0.3 on 2022-04-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subbackend', '0002_remove_subsdetails_subscriptionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='Status',
        ),
    ]
